assignValues:
  assign:
    daysOfWeek: ${incoming.body.daysOfWeek}
    fromDate: ${incoming.body.fromDate}
    rasaFolds: ${incoming.body.rasaFolds}
    scheduled: ${incoming.body.scheduled}
    modifierId: ${incoming.body.modifierId}
    modifierName: ${incoming.body.modifierName}
#  next: checkEntity

updateInDatabase:
  call: http.post
  args:
    url: "[#TRAINING_RESQL]/add-train-settings"
    body:
      days_of_week: ${daysOfWeek}
      from_date: ${fromDate}
      rasa_folds: ${rasaFolds}
      scheduled: ${scheduled}
      modifier_id: ${modifierId}
      modifier_name: ${modifierName}
  result: dbResult

returnSuccess:
  return: 'Updated Successfully.'
  wrapper: false
  next: end

checkEntity:
  call: http.post
  args:
    url: "[#TRAINING_DMAPPER]/dmapper/checkV"
    body:
      hits: ${incoming.body}
  result: fileResult