assignValues:
  assign:
    daysofweek: ${incoming.body.daysofweek}
    fromdate: ${incoming.body.fromdate}
    folds: ${incoming.body.folds}
    scheduled: ${incoming.body.scheduled}

updateInDatabase:
  call: http.post
  args:
    url: "[#TRAINING_RESQL]/add-train-settings"
    body:
      daysofweek: ${daysofweek}
      fromdate: ${fromdate}
      folds: ${folds}
      scheduled: ${scheduled}
  result: dbResult

returnSuccess:
  return: 'Updated Successfully.'
  wrapper: false
  next: end
